In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, np.nan, 30, 32, 22],
    'Salary': [50000, 60000, np.nan, 52000, np.nan],
    'Department': ['HR', 'IT', 'IT', np.nan, 'Finance']
}

In [3]:
df = pd.DataFrame(data)
print(df)

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

#### Types of Missing Values
* MCAR (Missing Completely at Random) -> Missingness occurs randomly and is not related to any variable in the dataset.
* MAR (Missing at Random) -> Missingness depends on other observed variables, not on the missing value itself.
* MNAR (Missing Not at Random) -> Missingness is directly related to the value that is missing.

#### Methods for detecting Missing data

### 1)

In [4]:
df.isnull()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False  False    True       False

In [5]:
df.isnull().sum()

Name          0
Age           1
Salary        2
Department    1
dtype: int64

### 2)

In [6]:
df.notnull()

   Name    Age  Salary  Department
0  True   True    True        True
1  True  False    True        True
2  True   True   False        True
3  True   True    True       False
4  True   True   False        True

In [7]:
df.notnull().sum()

Name          5
Age           4
Salary        3
Department    4
dtype: int64

### 3)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         4 non-null      float64
 2   Salary      3 non-null      float64
 3   Department  4 non-null      object
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

### 4)

In [12]:
df.isna()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False  False    True       False

In [13]:
df.isna().sum()

Name          0
Age           1
Salary        2
Department    1
dtype: int64

### 5)

In [14]:
df_copy = df.copy()
df_copy.dropna()

    Name   Age   Salary Department
0  Alice  25.0  50000.0         HR

In [15]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

### 6)

In [19]:
df_copy = df.copy()
df_copy.fillna(value='!')

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob     !  60000.0         IT
2  Charlie  30.0        !         IT
3    David  32.0  52000.0          !
4      Eva  22.0        !    Finance

In [20]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

### 7)

In [24]:
df_copy = df.copy()
df_copy.replace(np.nan, '!')

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob     !  60000.0         IT
2  Charlie  30.0        !         IT
3    David  32.0  52000.0          !
4      Eva  22.0        !    Finance

### 8)

In [25]:
df_copy = df.copy()
df_copy.drop_duplicates()

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

### 9)

In [ ]:
df['Age'].unique()

array([25., nan, 30., 32., 22.])

In [29]:
df['Department'].unique()

array(['HR', 'IT', nan, 'Finance'], dtype=object)

In [30]:
df['Name'].unique()

array(['Alice', 'Bob', 'Charlie', 'David', 'Eva'], dtype=object)

In [31]:
df['Salary'].unique()

array([50000., 60000.,    nan, 52000.])

### Imputation Methods