In [211]:
import pandas as pd
import numpy as np

In [212]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, np.nan, 30, 32, 22],
    'Salary': [50000, 60000, np.nan, 52000, np.nan],
    'Department': ['HR', 'IT', 'IT', np.nan, 'Finance']
}

In [213]:
df = pd.DataFrame(data)
print(df)

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

#### Types of Missing Values
* MCAR (Missing Completely at Random) -> Missingness occurs randomly and is not related to any variable in the dataset.
* MAR (Missing at Random) -> Missingness depends on other observed variables, not on the missing value itself.
* MNAR (Missing Not at Random) -> Missingness is directly related to the value that is missing.

#### Methods for detecting Missing data

### 1)

In [214]:
df.isnull()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False  False    True       False

In [215]:
df.isnull().sum()

Name          0
Age           1
Salary        2
Department    1
dtype: int64

### 2)

In [216]:
df.notnull()

   Name    Age  Salary  Department
0  True   True    True        True
1  True  False    True        True
2  True   True   False        True
3  True   True    True       False
4  True   True   False        True

In [217]:
df.notnull().sum()

Name          5
Age           4
Salary        3
Department    4
dtype: int64

### 3)

In [218]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      object
 1   Age         4 non-null      float64
 2   Salary      3 non-null      float64
 3   Department  4 non-null      object
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

### 4)

In [219]:
df.isna()

    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True       False
3  False  False   False        True
4  False  False    True       False

In [220]:
df.isna().sum()

Name          0
Age           1
Salary        2
Department    1
dtype: int64

### 5)

In [221]:
df_copy = df.copy()
df_copy.dropna()

    Name   Age   Salary Department
0  Alice  25.0  50000.0         HR

In [222]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

### 6)

In [223]:
df_copy = df.copy()
df_copy.fillna(value='!')

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob     !  60000.0         IT
2  Charlie  30.0        !         IT
3    David  32.0  52000.0          !
4      Eva  22.0        !    Finance

In [224]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

### 7)

In [225]:
df_copy = df.copy()
df_copy.replace(np.nan, '!')

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob     !  60000.0         IT
2  Charlie  30.0        !         IT
3    David  32.0  52000.0          !
4      Eva  22.0        !    Finance

### 8)

In [226]:
df_copy = df.copy()
df_copy.drop_duplicates()

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

### 9)

In [227]:
df['Age'].unique()

array([25., nan, 30., 32., 22.])

In [228]:
df['Department'].unique()

array(['HR', 'IT', nan, 'Finance'], dtype=object)

In [229]:
df['Name'].unique()

array(['Alice', 'Bob', 'Charlie', 'David', 'Eva'], dtype=object)

In [230]:
df['Salary'].unique()

array([50000., 60000.,    nan, 52000.])

### Imputation Methods

#### 1) Mean, Median and Mode Imputation

##### The imputations in these examples are for practice purposes only and do not necessarily reflect real-world usage !!!

In [231]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

In [232]:
mean_imp = df['Age'].fillna(round(df['Age'].mean(), 0))
median_imp = df['Salary'].fillna(df['Salary'].median())
mode_imp = df['Department'].fillna(df['Department'].mode().iloc[0])

In [233]:
mean_imp

0    25.0
1    27.0
2    30.0
3    32.0
4    22.0
Name: Age, dtype: float64

In [234]:
median_imp

0    50000.0
1    60000.0
2    52000.0
3    52000.0
4    52000.0
Name: Salary, dtype: float64

In [235]:
mode_imp

0         HR
1         IT
2         IT
3         IT
4    Finance
Name: Department, dtype: object

#### 2) Forward and Backward Fill

In [236]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

In [237]:
forward_fill = df['Age'].ffill()

In [238]:
forward_fill

0    25.0
1    25.0
2    30.0
3    32.0
4    22.0
Name: Age, dtype: float64

In [239]:
backward_fill = df['Age'].bfill()

In [240]:
backward_fill

0    25.0
1    30.0
2    30.0
3    32.0
4    22.0
Name: Age, dtype: float64

#### 3) Interpolation Techniques

In [241]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

In [242]:
linear = df['Salary'].interpolate(method='linear')
quadratic = df['Salary'].interpolate(method='quadratic')

In [243]:
linear

0    50000.0
1    60000.0
2    56000.0
3    52000.0
4    52000.0
Name: Salary, dtype: float64

In [244]:
quadratic

0    50000.000000
1    60000.000000
2    60666.666667
3    52000.000000
4             NaN
Name: Salary, dtype: float64

## Sklearn Imputers

In [245]:
from sklearn.impute import SimpleImputer

In [246]:
df

      Name   Age   Salary Department
0    Alice  25.0  50000.0         HR
1      Bob   NaN  60000.0         IT
2  Charlie  30.0      NaN         IT
3    David  32.0  52000.0        NaN
4      Eva  22.0      NaN    Finance

In [247]:
imputer = SimpleImputer(strategy='median')

#### For now, for the purpose of practice I will try to make X_train and X_test dataframes to only have numeric columns since fitting and transforming without proper pipeline is applied to all columns.

In [248]:
X_train = df.loc[:4].drop(['Name', 'Department'], axis=1)
X_test = df.loc[4].to_frame().T.drop(['Name', 'Department'], axis=1)

In [249]:
X_train

    Age   Salary
0  25.0  50000.0
1   NaN  60000.0
2  30.0      NaN
3  32.0  52000.0
4  22.0      NaN

In [250]:
X_test

    Age Salary
4  22.0    NaN

In [251]:
train_columns = X_train.columns
train_index = X_train.index

test_columns = X_test.columns
test_index = X_test.index

In [252]:
train_columns

Index(['Age', 'Salary'], dtype='object')

In [253]:
train_index

RangeIndex(start=0, stop=5, step=1)

In [254]:
test_columns

Index(['Age', 'Salary'], dtype='object')

In [255]:
test_index

Index([4], dtype='int64')

In [256]:
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

In [257]:
X_train = pd.DataFrame(X_train, columns=train_columns, index=train_index)
X_test = pd.DataFrame(X_test, columns=test_columns, index=test_index)

In [258]:
X_train

    Age   Salary
0  25.0  50000.0
1  27.5  60000.0
2  30.0  52000.0
3  32.0  52000.0
4  22.0  52000.0

In [259]:
X_test

    Age   Salary
4  22.0  52000.0