In [51]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [52]:
X = [
    {
        'age': 20,
        'salary': 3000
    },
    {
        'age': 30,
        'salary': 5000
    },
    {
        'age': 40,
        'salary': 8000
    },
    {
        'age': 50,
        'salary': 12000
    }
]

X = pd.DataFrame(X)
y = pd.DataFrame(X['salary'])
X = pd.DataFrame(X['age'])

In [53]:
X

   age
0   20
1   30
2   40
3   50

In [54]:
y

   salary
0    3000
1    5000
2    8000
3   12000

In [55]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=123
)

In [56]:
X_train

   age
0   20
1   30
2   40

In [57]:
y_train

   salary
0    3000
1    5000
2    8000

In [58]:
X_test

   age
3   50

In [59]:
y_test

   salary
3   12000

In [60]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('model', LogisticRegression())
])

In [61]:
pipeline.fit(X_train, y_train);

c:\Users\konta\anaconda3\envs\ds\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [62]:
predictions = pipeline.predict(X_test)

In [63]:
predictions

array([8000])